############################################
# APP
############################################
spring.application.name=insighthub
server.port=${PORT:8080}

############################################
# DATASOURCE (PROD) - reads from Cloud Run ENV
############################################
spring.datasource.url=${SPRING_DATASOURCE_URL}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

############################################
# JPA / HIBERNATE
############################################
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.open-in-view=false
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=false
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

############################################
# SQL INIT (optional)
############################################
spring.sql.init.mode=never

############################################
# LOGGING (keep prod clean)
############################################
logging.level.org.springframework=INFO
logging.level.org.hibernate.SQL=INFO